### ISSUE TITLE
TP car

### ISSUE THREAD

**Issue by btwentyone** [qalle-fivem/esx_teleports#1]
Hello, by changing something in the code, we can teleport with the car?

Thank you in advance for your answer because I can not do it unfortunately.

**Comment by qalle-git** [comment]
Yes it's doable i can do that.

**Comment by btwentyone** [comment]
@qalle-fivem 
Good evening, if it's feasible, I can have a lot of people will like it because I'm a bit of a blocker.
Thanks to you in advance

**Comment by Dannytb98** [comment]
Is there anyway you can make this to be able to teleport with vehicle if job == 'mechanic'?  if so, how? Thanks.

**Comment by Solestra** [comment]
Hello, a maj for the TP vehicle?
